version: '3'

services:
  geography-db:
    container_name: geography-db
    hostname: geography-db
    image: yemax/geography-mongodb:v1
    expose:
      - "27017"
  geography-server:
    container_name: geography-server
    image: yemax/geography-api:v1
    links:
      - geography-db
    expose:
      - "4000"