version: '3.6'

services:
  geography-db:
    container_name: geography-db
    hostname: geography-db
    build: 01_DB/.
    ports:
      - '27017:27017'

  geography-server:
    container_name: geography-server
    hostname: geography-server
    build:
      context: 02_Server/.
      dockerfile: Dockerfile.compose
    depends_on:
      - geography-db
    ports:
      - '4003:4000'
    command: sh wait-mongo.sh
