FROM node:8.14-alpine

LABEL mantainer="egormaksimchuk@gmail.com"

WORKDIR /usr/src/app

COPY package.json /usr/src/app
RUN npm install && npm install -g nodemon
COPY . .

EXPOSE 4000

CMD ["nodemon", "app.js"]